package pokemonBattleJUnit;

public enum PokemonName {

	// simplified to 1 type

	// @formatter:off
	BULBASAUR(Type.GRASS), IVYSAUR(Type.GRASS), VENUSAUR(Type.GRASS), CHARMANDER(Type.FIRE), CHARMELEON(Type.FIRE), CHARIZARD(Type.FIRE), SQUIRTLE(Type.WATER), WARTORTLE(Type.WATER), BLASTOISE(Type.WATER), CATERPIE(Type.BUG), METAPOD(Type.BUG), BUTTERFREE(Type.BUG), WEEDLE(Type.BUG), KAKUNA(Type.BUG), BEEDRILL(Type.BUG), PIDGEY(Type.FLYING), PIDGEOTTO(Type.FLYING), PIDGEOT(Type.FLYING), RATTATA(Type.NORMAL), RATICATE(Type.NORMAL), SPEAROW(Type.FLYING), FEAROW(Type.FLYING), EKANS(Type.POISON), ARBOK(Type.POISON), PIKACHU(Type.ELECTRIC), RAICHU(Type.ELECTRIC), SANDSHREW(Type.GROUND), SANDSLASH(Type.GROUND), NIDORAN(Type.GROUND), NIDORINA(Type.GROUND), NIDOQUEEN(Type.GROUND), NIDORINO(Type.GROUND), NIDOKING(Type.GROUND), CLEFAIRY(Type.NORMAL), CLEFABLE(Type.NORMAL), VULPIX(Type.FIRE), NINETALES(Type.FIRE), JIGGLYPUFF(Type.NORMAL), WIGGLYTUFF(Type.NORMAL), ZUBAT(Type.FLYING), GOLBAT(Type.FLYING), ODDISH(Type.GRASS), GLOOM(Type.GRASS), VILEPLUME(Type.GRASS), PARAS(Type.GRASS), PARASECT(Type.GRASS), VENONAT(Type.BUG), VENOMOTH(Type.BUG), DIGLETT(Type.GROUND), DUGTRIO(Type.GROUND), MEOWTH(Type.NORMAL), PERSIAN(Type.NORMAL), PSYDUCK(Type.WATER), GOLDUCK(Type.WATER), MANKEY(Type.FIGHTING), PRIMEAPE(Type.FIGHTING), GROWLITHE(Type.FIRE), ARCANINE(Type.FIRE), POLIWAG(Type.WATER), POLIWHIRL(Type.WATER), POLIWRATH(Type.WATER), ABRA(Type.PSYCHIC), KADABRA(Type.PSYCHIC), ALAKAZAM(Type.PSYCHIC), MACHOP(Type.FIGHTING), MACHOKE(Type.FIGHTING), MACHAMP(Type.FIGHTING), BELLSPROUT(Type.GRASS), WEEPINBELL(Type.GRASS), VICTREEBEL(Type.GRASS), TENTACOOL(Type.WATER), TENTACRUEL(Type.WATER), GEODUDE(Type.ROCK), GRAVELER(Type.ROCK), GOLEM(Type.ROCK), PONYTA(Type.FIRE), RAPIDASH(Type.FIRE), SLOWPOKE(Type.WATER), SLOWBRO(Type.WATER), MAGNEMITE(Type.ELECTRIC), MAGNETON(Type.ELECTRIC), FARFETCHD(Type.FLYING), DODUO(Type.NORMAL), DODRIO(Type.NORMAL), SEEL(Type.ICE), DEWGONG(Type.ICE), GRIMER(Type.POISON), MUK(Type.POISON), SHELLDER(Type.WATER), CLOYSTER(Type.ICE), GASTLY(Type.GHOST), HAUNTER(Type.GHOST), GENGAR(Type.GHOST), ONIX(Type.ROCK), DROWZEE(Type.PSYCHIC), HYPNO(Type.PSYCHIC), KRABBY(Type.WATER), KINGLER(Type.WATER), VOLTORB(Type.ELECTRIC), ELECTRODE(Type.ELECTRIC), EXEGGCUTE(Type.GRASS), EXEGGUTOR(Type.GRASS), CUBONE(Type.GROUND), MAROWAK(Type.GROUND), HITMONLEE(Type.FIGHTING), HITMONCHAN(Type.FIGHTING), LICKITUNG(Type.NORMAL), KOFFING(Type.POISON), WEEZING(Type.POISON), RHYHORN(Type.GROUND), RHYDON(Type.GROUND), CHANSEY(Type.NORMAL), TANGELA(Type.GRASS), KANGASKHAN(Type.NORMAL), HORSEA(Type.WATER), SEADRA(Type.WATER), GOLDEEN(Type.WATER), SEAKING(Type.WATER), STARYU(Type.WATER), STARMIE(Type.WATER), MR_MIME(Type.PSYCHIC), SCYTHER(Type.BUG), JYNX(Type.ICE), ELECTABUZZ(Type.ELECTRIC), MAGMAR(Type.FIRE), PINSIR(Type.BUG), TAUROS(Type.NORMAL), MAGIKARP(Type.WATER), GYARADOS(Type.WATER), LAPRAS(Type.ICE), DITTO(Type.NORMAL), EEVEE(Type.NORMAL), VAPOREON(Type.WATER), JOLTEON(Type.ELECTRIC), FLAREON(Type.FIRE), PORYGON(Type.NORMAL), OMANYTE(Type.ROCK), OMASTAR(Type.ROCK), KABUTO(Type.ROCK), KABUTOPS(Type.ROCK), AERODACTYL(Type.FLYING), SNORLAX(Type.NORMAL), ARTICUNO(Type.ICE), ZAPDOS(Type.ELECTRIC), MOLTRES(Type.FIRE), DRATINI(Type.DRAGON), DRAGONAIR(Type.DRAGON), DRAGONITE(Type.DRAGON), MEWTWO(Type.PSYCHIC), MEW(Type.PSYCHIC);
	// @formatter:ON
	private Type type;

	PokemonName(Type type) {
		this.type = type;
	}

	public Type getType() {
		return type;
	}
}
